### ISSUE TITLE
Invalid solutions found for quartic poly

### ISSUE THREAD

**Issue by EmanueleSiego** [ebertolazzi/quarticRootsFlocke#1]
Solving the following poly, it gives two invalid solutions:
_p(x) = a*x^4 + b*x^3 + c*x^2 + d*x + e
a = 714285.71428571432
b = -100000
c = 13479.924671428573
d = -2.2737367544323206e-13
e = -22.526485131747265_

Matlab solutions with 'roots' are:
_r1 = 0.064423196657504 + 0.122215870576901i
r2 = 0.064423196657504 - 0.122215870576901i
r3 = 0.046605762356559
r4 = -0.035452155671566_

**Comment by EmanueleSiego** [comment]
Thanks, I'll wait for the commit :-)

**Comment by ebertolazzi** [comment]
I renamed the repo quarticRootsFlocke because it is the implementation of the algorithm of Flocke
(doi: 10.1145/2699468).
