### ISSUE TITLE
Invalid solution found for quartic poly

### ISSUE THREAD

**Issue by EmanueleSiego** [ebertolazzi/quarticRootsFlocke#2]
Solving the following poly, it gives invalid solutions for complex roots and one real root:
p(x) = ax^4 + bx^3 + cx^2 + dx + e
a = -5.898376305898030e-09
b = -6.000000000001007e+06
c = 3.664603343001005e-27
d = 0
e = 9.000000000003021e+02

Matlab solutions with 'roots' are:
r1 = -1.017229096421223e+15
r2 = -0.026566464600067 + 0.046014465225927i
r3 = -0.026566464600067 - 0.046014465225927i
r4 = 0.053132929200150

For example the root residual for r4 is:
-  -3.765546080103377e-05 with Matlab
-  9.000000000003021e+02 with quarticRootsFlocke

Setting _a_ coeffient to 0 the solution is correct. It seems an ill-conditioned problem.

**Comment by ebertolazzi** [comment]
There was an wrong selection of the root for the deflaction with consequent hill condition. Now should be solved.
