### ISSUE TITLE
Neverending loop for quartic poly

### ISSUE THREAD

**Issue by EmanueleSiego** [ebertolazzi/quarticRootsFlocke#3]
Consider the quartic poly:
```
double c4 = 5.0 * ( -1462.2326183798939 );
double c3 = 4.0 * ( 1868.4944990527565 );
double c2 = 3.0 * ( -901.83171888631921 );
double c1 = 2.0 * ( 206.27445843560130 );
double c0 = 1.0 * ( -23.818259047289210 );
```
The following method call goes into a neverending loop:
```
double re[4], im[4];
int n = QuarticGetRoots( c4, c3, c2, c1, c0, re, im );
```
Debugging the code, there's a division by 0 inside _zeroQuarticByNewtonBisection_ method:
`x -= p/dp`
with dp = 0.
Changing a little the poly coeffs (i.e. using c4 = -5.0 * 1462.232618379893) it gives the correct results.
The issue has been debugged with VS2013 and VS2019 using the commit _bc377b5fc3a794db06473495e0d25226e45c9886_

**Comment by EmanueleSiego** [comment]
Testing for root already found before entering Newton iterations seems to solve the issue:

```
static
  indexType
  zeroQuarticByNewtonBisection(
    valueType  a,
    valueType  b,
    valueType  c,
    valueType  d,
    valueType & x
  ) {
    valueType p, dp;
    evalMonicQuartic( x, a, b, c, d, p, dp );
    valueType t = p; // save p(x) for sign comparison
    if ( p == 0.0 ) return 0; // <-- TESTING FOR ROOT ALREADY FOUND -->
    x -= p/dp; // 1st improved root
    // ...
```
I don't know if it's robust enough from numerical point of view. Maybe a tolerance should be used.

**Comment by EmanueleSiego** [comment]
I've also noted that _NewtonBisection_ method does not stop within a fixed maximum number of iterations.

```
while ( ! (converged||bisection) ) { // <-- NEVERENDING LOOP COULD HAPPEN HERE
      ++iter;
      evalMonicCubic( x, a, b, c, p, dp );
      if ( p*t < 0 ) { // does Newton start oscillating ?
        if ( p < 0 ) {
          ++oscillate; // increment oscillation counter
          s = x;       // save lower bisection bound
        } else {
          u = x; // save upper bisection bound
        }
        t = p; // save current p(x)
      }
      dp = p/dp; // Newton correction
      x -= dp;   // new Newton root
      bisection = oscillate > 2; // activate bisection
      converged = std::abs(dp) <= std::abs(x) * machepsi; // Newton convergence indicator
    }
```

**Comment by ebertolazzi** [comment]
The loop do not end when x --> 0 thus changing std::abs(x) * machepsi with (1+std::abs(x)) * machepsi solve the problem.

**Comment by EmanueleSiego** [comment]
The fix solves the problem with the posted input data, but I had another case that behaves like an infinite loop. At the moment I don't have the input data for this case.
I saw that the fix has been applied only in method _NewtonBisection_ but method _zeroQuarticByNewtonBisection_ has a similar algorithm structure. Maybe it should be fixed too?

**Comment by ebertolazzi** [comment]
Made a similar fix for the cubic root, now should work.

**Comment by EmanueleSiego** [comment]
Unfortunately the fix in the last commit (3d0259d28b4baa6b7f518205ae02d387a0cd9d28) does not solve all cases.
Here the input data of a new case:
```
double re[4], im[4];
double c4 = 5.0 * ( -4.1254841444253390e+02 );
double c3 = 4.0 * ( 5.9401042551598744e+02 );
double c2 = 3.0 * ( -3.1743361677460911e+02 );
double c1 = 2.0 * ( 7.7477065082592929e+01 );
double c0 = 1.0 * ( -8.9469482641160880e+00 );
int n = QuarticGetRoots( c4, c3, c2, c1, c0, re, im );
```
The problem happens solving the cubic poly obtained after quartic poly deflation. Using the workaround in https://github.com/ebertolazzi/quarticRootsFlocke/issues/3#issuecomment-745963261 (`if ( p == 0.0 ) return 0; // <-- TESTING FOR ROOT ALREADY FOUND -->`) the loop is avoided and the solution is correct (compared with Matlab one). Maybe using _machepsi_ tolerance in the test is a better way.

Some other notes not scrictly related to this case:

- _zeroHexicByNewtonBisection_ method has the same structure of _zeroQuarticByNewtonBisection_ method but it has not been fixed
- _zeroQuarticByNewtonBisection_ method check for iter < 50 but _NewtonBisection_ is not

**Comment by ebertolazzi** [comment]
The problem happen when we have a double real root (not covered in the paper).
When this is detected is enough to skip refinement and solver work well.

**Comment by EmanueleSiego** [comment]
With your last fix I have not found infinite loops anymore.
Great! I think you can close the ticket. Thanks.

**Comment by ebertolazzi** [comment]
Thanks a lot!.
