### ISSUE TITLE
Different found roots for Quartic poly after update

### ISSUE THREAD

**Issue by EmanueleSiego** [ebertolazzi/quarticRootsFlocke#7]
Updating from commit fa763d2b6f38269e896bd41604b793d92b3186e8 to commit c0be6720ee887e4da47c3998c5e9e2ba32ab3d8f I get different solutions for the following Quartic poly:

p = [86594.643180459301, -509.64355468067714, 0.74986322275510664, 0.0000000000000000, -1.7386537088520670e-16]

Old roots (all real):
r0 = -1.5226962261856962e-08
r1 = 1.5227119847090433e-08
r2 = 0.0029426967763176593
r3 = 0.0029426967763176593

New roots (2 real, 2 complex):
r0 = 0.0029426967762312241 + i * 2.2554513436451675e-08
r1 = 0.0029426967762312241 - i * 2.2554513436451675e-08
r2 = -1.5226962261856962e-08
r3 = 1.5227119847090433e-08

Matlab solutions match with the old version.

**Comment by EmanueleSiego** [comment]
It seems the "problem" is related to _b1_ initialization in _PolynomialRoots-2-Cubic.cc_ file: using the old version `b1 = aa+r2`, roots match with Matlab ones.

Code:
```
valueType b0 = -cc/r2;
//valueType b1 = aa+r2; // changed deflaction, seems more accurate
valueType b1 = (b0-bb)/r2;
```

**Comment by ebertolazzi** [comment]
Thanks for the debug. I put a workaround that try to obtain the best accuracy:

     valueType b0 = -cc/r2;
     valueType b1 = std::abs(r2) < 1 ? aa+r2 : -(cc/r2+bb)/r2;

However the true solution is to use quadruple precision (or a different algorithm).
